### ISSUE TITLE
Met AttributeError: 'NoneType' object has no attribute 'upper'

### ISSUE THREAD

**Issue by chunyunchen** [openshift/django-ex#1]
1) Login openshift and create project for the user

$ osc login --server=$master -u $user -p $password
$ osc new-project test

  2) Create imageStream

$ osc create -f image-streams-centos7.json
(the file "image-streams-centos7.json" is same with https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json)

 3) Login openshift in web console

 4) Create application in console

   "Create.." -> Input repo url "https://github.com/openshift/django-ex" -> "Next" -> Select a builder image "python:latest" -> finish create

 5) Start a build in webconsole

   Browse -> Builds -> "Start Build"

 6) Wait build complete and check the log of pod

$ osc get pod
$ osc log django-ex-1-y6hc1

*****************log messages as below*********************
+ python manage.py migrate --noinput
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/openshift/src/.local/lib/python3.3/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/opt/openshift/src/.local/lib/python3.3/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/opt/openshift/src/.local/lib/python3.3/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/opt/openshift/src/.local/lib/python3.3/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/openshift/src/.local/lib/python3.3/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/rh/python33/root/usr/lib64/python3.3/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1586, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1567, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1534, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1024, in load_module
  File "<frozen importlib._bootstrap>", line 1005, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 870, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/opt/openshift/src/project/settings.py", line 87, in <module>
    'default': database.config()
  File "/opt/openshift/src/project/database.py", line 14, in config
    service_name = os.getenv('DATABASE_SERVICE_NAME').upper()
AttributeError: 'NoneType' object has no attribute 'upper'

**Comment by mfojtik** [comment]
@rhcarvalho PTAL ^
