### ISSUE TITLE
Django version in requirements.txt

### ISSUE THREAD

**Issue by hmleal** [openshift/django-ex#38]
Django 1.8.X is the LTS version and has support until at least April 2018 why not update the requirements.txt to:

```
django==1.8.1 # now
django<=1.9
```

**Comment by bparees** [comment]
unfortunately that appears to cause the post-commit hook tests (`./manage.py test`) to fail:

```
I0408 04:14:20.891406       1 dockerutil.go:199] Starting container "openshift_s
2i-build_django-psql-example-3_p1_post-commit_5ff41648" ...
I0408 04:14:21.115965       1 dockerutil.go:206] Streaming logs of container "openshift_s2i-build_django-psql-example-3_p1_post-commit_5ff41648" with options {Container:5e7793822594b041f52a66a39e730f31abbd8161d2438e70b1d4b17f8017f83b OutputStream:0xc82002a010 ErrorStream:0xc82002a018 Follow:true Stdout:true Stderr:true Since:0 Timestamps:false Tail: RawTerminal:false} ...
sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell
Traceback (most recent call last):
  File "/opt/app-root/src/.local/lib/python3.4/site-packages/debug_toolbar/toolbar.py", line 127, in get_panel_classes
    mod = import_module(panel_module)
  File "/opt/rh/rh-python34/root/usr/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/opt/app-root/src/.local/lib/python3.4/site-packages/debug_toolbar/panels/__init__.py", line 8, in <module>
    from debug_toolbar.utils import get_name_from_obj
  File "/opt/app-root/src/.local/lib/python3.4/site-packages/debug_toolbar/utils.py", line 19, in <module>
    from django.views.debug import linebreak_iter
ImportError: cannot import name 'linebreak_iter'

...................
```

**Comment by PI-Victor** [comment]
i wrote the tests for this so i can fix them, please assign it to me.

**Comment by PI-Victor** [comment]
it's not the tests, the django version needs django-debug-toolbar updated as well. 
but i will submit a PR these days upgrading all dependencies and fixing a few deprecated functions.

```
(venv2)[ipalade@redhat-openshiftlab django-ex] $ ./manage.py test
Traceback (most recent call last):
  File "/home/ipalade/projects/django-ex/venv2/lib/python3.4/site-packages/debug_toolbar/toolbar.py", line 127, in get_panel_classes
    mod = import_module(panel_module)
  File "/home/ipalade/projects/django-ex/venv2/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/ipalade/projects/django-ex/venv2/lib/python3.4/site-packages/debug_toolbar/panels/__init__.py", line 8, in <module>
    from debug_toolbar.utils import get_name_from_obj
  File "/home/ipalade/projects/django-ex/venv2/lib/python3.4/site-packages/debug_toolbar/utils.py", line 19, in <module>
    from django.views.debug import linebreak_iter
ImportError: cannot import name 'linebreak_iter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ipalade/projects/django-ex/venv2/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/ipalade/projects/django-ex/venv2/lib/python3.4/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/ipalade/projects/django-ex/venv2/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ipalade/projects/django-ex/venv2/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/ipalade/projects/django-ex/venv2/lib/python3.4/site-packages/debug_toolbar/apps.py", line 15, in ready
    dt_settings.patch_all()
  File "/home/ipalade/projects/django-ex/venv2/lib/python3.4/site-packages/debug_toolbar/settings.py", line 231, in patch_all
    patch_middleware_classes()
  File "/home/ipalade/projects/django-ex/venv2/lib/python3.4/site-packages/debug_toolbar/settings.py", line 210, in patch_middleware_classes
    if not is_toolbar_middleware_installed():
  File "/home/ipalade/projects/django-ex/venv2/lib/python3.4/site-packages/debug_toolbar/settings.py", line 190, in is_toolbar_middleware_installed
    from debug_toolbar.middleware import DebugToolbarMiddleware
  File "/home/ipalade/projects/django-ex/venv2/lib/python3.4/site-packages/debug_toolbar/middleware.py", line 14, in <module>
    from debug_toolbar.toolbar import DebugToolbar
  File "/home/ipalade/projects/django-ex/venv2/lib/python3.4/site-packages/debug_toolbar/toolbar.py", line 160, in <module>
    urlpatterns = DebugToolbar.get_urls()
  File "/home/ipalade/projects/django-ex/venv2/lib/python3.4/site-packages/debug_toolbar/toolbar.py", line 154, in get_urls
    for panel_class in cls.get_panel_classes():
  File "/home/ipalade/projects/django-ex/venv2/lib/python3.4/site-packages/debug_toolbar/toolbar.py", line 131, in get_panel_classes
    (panel_module, e))
django.core.exceptions.ImproperlyConfigured: Error importing debug panel debug_toolbar.panels.versions: "cannot import name 'linebreak_iter'"
(venv2)[ipalade@redhat-openshiftlab django-ex] $ pip3 install django-debug-toolbar
You are using pip version 6.0.8, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): django-debug-toolbar in ./venv2/lib/python3.4/site-packages
Requirement already satisfied (use --upgrade to upgrade): sqlparse in ./venv2/lib/python3.4/site-packages (from django-debug-toolbar)
Requirement already satisfied (use --upgrade to upgrade): django>=1.4.2 in ./venv2/lib/python3.4/site-packages (from django-debug-toolbar)
(venv2)[ipalade@redhat-openshiftlab django-ex] $ pip3 install django-debug-toolbar --upgrade
You are using pip version 6.0.8, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting django-debug-toolbar from https://pypi.python.org/packages/2.7/d/django-debug-toolbar/django_debug_toolbar-1.4-py2.py3-none-any.whl#md5=536799486f5f7ba79f80fa6e840f333b
  Using cached django_debug_toolbar-1.4-py2.py3-none-any.whl
Requirement already up-to-date: Django>=1.7 in ./venv2/lib/python3.4/site-packages (from django-debug-toolbar)
Requirement already up-to-date: sqlparse in ./venv2/lib/python3.4/site-packages (from django-debug-toolbar)
Installing collected packages: django-debug-toolbar
  Found existing installation: django-debug-toolbar 1.3.0
    Uninstalling django-debug-toolbar-1.3.0:
      Successfully uninstalled django-debug-toolbar-1.3.0

Successfully installed django-debug-toolbar-1.4
(venv2)[ipalade@redhat-openshiftlab django-ex] $ ./manage.py test
/home/ipalade/projects/django-ex/project/urls.py:9: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got welcome.views.index). Pass the callable instead.
  url(r'^$', 'welcome.views.index'),

/home/ipalade/projects/django-ex/project/urls.py:10: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got welcome.views.health). Pass the callable instead.
  url(r'^health$', 'welcome.views.health'),

Creating test database for alias 'default'...
...
----------------------------------------------------------------------
Ran 3 tests in 0.012s

OK
Destroying test database for alias 'default'...

```
