### ISSUE TITLE
Hello, I tried to run the code, but it shows

### ISSUE THREAD

**Issue by qwelin** [openshift/django-ex#71]
Hello, I tried to run the code, but it shows：
django.core.exceptions.ImproperlyConfigured: WSGI application 'application' could not be loaded; Error importing module: 'application doesn't look like a module path'

**Comment by PI-Victor** [comment]
can you be a bit more specific? where does this error appear, on openshift, on your local system, did you follow all of the steps provided in the [README.md](https://github.com/openshift/django-ex#local-development), are you running the example or your own example?
I'm familiar with this error, but i don't exactly remember where i saw it before, or how i bumped into it. It's not an error in the example, though.

**Comment by qwelin** [comment]
on mine local system,liunx.yes ,  I was follow all of the steps provided in the README.md and I running the example.

(text_1) MacxdeMacBook-Pro-251:django-ex will$ ./manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
December 22, 2016 - 10:15:46
Django version 1.8, using settings 'project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10431f730>
Traceback (most recent call last):
  File "/Users/Macx/text_1/lib/python3.5/site-packages/django/utils/module_loading.py", line 21, in import_string
    module_path, class_name = dotted_path.rsplit('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Macx/text_1/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 50, in get_internal_wsgi_application
    return import_string(app_path)
  File "/Users/Macx/text_1/lib/python3.5/site-packages/django/utils/module_loading.py", line 24, in import_string
    six.reraise(ImportError, ImportError(msg), sys.exc_info()[2])
  File "/Users/Macx/text_1/lib/python3.5/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/Users/Macx/text_1/lib/python3.5/site-packages/django/utils/module_loading.py", line 21, in import_string
    module_path, class_name = dotted_path.rsplit('.', 1)
ImportError: application doesn't look like a module path

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Macx/text_1/lib/python3.5/site-packages/django/utils/autoreload.py", line 223, in wrapper
    fn(*args, **kwargs)
  File "/Users/Macx/text_1/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 137, in inner_run
    handler = self.get_handler(*args, **options)
  File "/Users/Macx/text_1/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 24, in get_handler
    handler = super(Command, self).get_handler(*args, **options)
  File "/Users/Macx/text_1/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 55, in get_handler
    return get_internal_wsgi_application()
  File "/Users/Macx/text_1/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 60, in get_internal_wsgi_application
    sys.exc_info()[2])
  File "/Users/Macx/text_1/lib/python3.5/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/Users/Macx/text_1/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 50, in get_internal_wsgi_application
    return import_string(app_path)
  File "/Users/Macx/text_1/lib/python3.5/site-packages/django/utils/module_loading.py", line 24, in import_string
    six.reraise(ImportError, ImportError(msg), sys.exc_info()[2])
  File "/Users/Macx/text_1/lib/python3.5/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/Users/Macx/text_1/lib/python3.5/site-packages/django/utils/module_loading.py", line 21, in import_string
    module_path, class_name = dotted_path.rsplit('.', 1)
**django.core.exceptions.ImproperlyConfigured: WSGI application 'application' could not be loaded; Error importing module: 'application doesn't look like a module path'**

I tried setting WSGI_APPLICATION = on settings.py, but it still does not work

**Comment by jerinpetergeorge** [comment]
I got this issue.

I made small change in  **settings.py**

I changed `WSGI_APPLICATION = 'application'` to `WSGI_APPLICATION = 'wsgi.application'`

**Comment by StoneCX** [comment]
got same issue and above is not useful to me

**Comment by jerinpetergeorge** [comment]
> got same issue and above is not useful to me

got any error traceback?

**Comment by saddam1234567** [comment]
django.core.exceptions.ImproperlyConfigured: WSGI application 'demo.wsgi.applica
tion' could not be loaded; Error importing module.

**Comment by frenzymadness** [comment]
> django.core.exceptions.ImproperlyConfigured: WSGI application 'demo.wsgi.applica
> tion' could not be loaded; Error importing module.

As before, could you please be more specific and provide some info about your setup, complete traceback and so on.

**Comment by avraam1616** [comment]
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Windows\.virtualenvs\BLOG\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Windows\.virtualenvs\BLOG\lib\site-packages\django\core\handlers\base.py", line 202, in _get_response
    response = response.render()
  File "C:\Users\Windows\.virtualenvs\BLOG\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\Windows\.virtualenvs\BLOG\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\Windows\.virtualenvs\BLOG\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Windows\.virtualenvs\BLOG\lib\site-packages\django\template\base.py", line 168, in render
    with context.bind_template(self):
  File "C:\Users\Windows\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\Windows\.virtualenvs\BLOG\lib\site-packages\django\template\context.py", line 240, in bind_template
    processors = (template.engine.template_context_processors +
  File "C:\Users\Windows\.virtualenvs\BLOG\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Windows\.virtualenvs\BLOG\lib\site-packages\django\template\engine.py", line 85, in template_context_processors
    return tuple(import_string(path) for path in context_processors)
  File "C:\Users\Windows\.virtualenvs\BLOG\lib\site-packages\django\template\engine.py", line 85, in <genexpr>
    return tuple(import_string(path) for path in context_processors)
  File "C:\Users\Windows\.virtualenvs\BLOG\lib\site-packages\django\utils\module_loading.py", line 13, in import_string
    module_path, class_name = dotted_path.rsplit('.', 1)
AttributeError: 'list' object has no attribute 'rsplit'
[15/Dec/2020 07:58:33] "GET / HTTP/1.1" 500 102474

**Comment by avraam1616** [comment]
please help i am searchimg 3 days now.  I follow the william vincent's book chapter 5

**Comment by PI-Victor** [comment]
Hi, @avraam1616 
i would suggest anyone landing here from google or any other sources to not post their problem here but [open a new repo issue](https://github.com/sclorg/django-ex/issues/new) so that their problem gets the proper attention. 

This issue is 4 years old.
